services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/location.d:/etc/nginx/location.d:ro
      - ./nginx/rewrite.d:/etc/nginx/rewrite.d:ro
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./nginx/var/log/nginx:/var/log/nginx
      # for nginx common error folder #
      - /data/maintenance:/data/maintenance
      # for nginx common error folder #
      - /var/www/html:/var/www/html
      - /data/mdt:/data/mitacmdt-new
      - /data/mio_class:/data/mio_class
      - /data/cyclo:/data/cyclo
      - /data/ebc:/app/ebc
    links:
      - php-fpm-8.2
      - php-fpm-7.4
      - apache

  apache:
    image: bitnami/apache:latest
    ports:
      - "8088:8080"
      - "8443:8443"
    volumes:
      - ./apache/myapp.conf:/vhosts/myapp.conf:ro
      - ./apache/certs:/certs:ro
      - /data/ebc:/app/ebc
    environment:
      - APACHE_DEFAULT_HTTP_PORT_NUMBER=8080
      - APACHE_DEFAULT_HTTPS_PORT_NUMBER=8443
    restart: always

  php-fpm-8.2:
    image: bitnami/php-fpm:8.2.24
    volumes:
      - /var/www/html:/var/www/html
      - /data/mdt:/data/mitacmdt-new
      - /data/mio_class:/data/mio_class
      - /data/cyclo:/data/cyclo
      - ./php/php.ini:/opt/bitnami/php/etc/php.ini
    restart: always

  php-fpm-7.4:
    image: bitnami/php-fpm:7.4.33
    volumes:
      - /data/ebc:/app/ebc
      - ./php/php.ini:/opt/bitnami/php/etc/php.ini
    restart: always