services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/location.d:/etc/nginx/location.d:ro
      - ./nginx/rewrite.d:/etc/nginx/rewrite.d:ro
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./nginx/var/log/nginx:/var/log/nginx
      # for nginx common error folder #
      - /data/maintenance:/data/maintenance:ro
      # for nginx common error folder #
      - /var/www/html:/var/www/html:ro
      - /data/mdt:/data/mitacmdt-new:ro
      # - /data/visionmax:/data/visionmax
      - /data/mio_class:/data/mio_class:ro
      - /data/cyclo:/data/cyclo:ro
      - /data/ebc:/app/ebc:ro
    links:
      - php-fpm-8.2
      - php-fpm-7.4
      - apache

  apache:
    image: bitnami/apache:latest
    ports:
      - "8088:8080"
      - "8443:8443"
    volumes:
      - ./apache/myapp.conf:/vhosts/myapp.conf:ro
      - ./apache/certs:/certs:ro
      - /data/ebc:/app/ebc
      - /data/ebc/config.php:/app/ebc/config.php:ro
      - /data/ebc/MctBackend/config.php:/app/ebc/MctBackend/config.php:ro
      - /data/ebc/MCTWEBMGT/config.php:/app/ebc/MCTWEBMGT/config.php:ro
      - /data/ebc/PartnerZone/config.php:/app/ebc/PartnerZone/config.php:ro
    environment:
      APACHE_DEFAULT_HTTP_PORT_NUMBER: 8080
      APACHE_DEFAULT_HTTPS_PORT_NUMBER: 8443
    restart: always

  php-fpm-8.2:
    # build:
    #   context: ./php/82
    #   dockerfile: Dockerfile
    # image: custom-php-fpm:8.2
    image: bitnami/php-fpm:8.2.24
    volumes:
      - /var/www/html:/var/www/html
      - /data/mdt:/data/mitacmdt-new
      - /data/mio_class:/data/mio_class
      # - /data/visionmax:/data/visionmax
      - /data/cyclo:/data/cyclo
      - ./php/php.ini:/opt/bitnami/php/etc/php.ini:ro
      - ./php/82/www.conf:/opt/bitnami/php/etc/php-fpm.d/www.conf
      - ./php/82/log:/var/log
      - /data/mdt/.env:/data/mitacmdt-new/.env:ro
      - /data/mio_class/tw/wp-config.php:/data/mio_class/tw/wp-config.php:ro
      - /data/mio_class/ru/wp-config.php:/data/mio_class/ru/wp-config.php:ro
    restart: always

  php-fpm-7.4:
    # build:
    #   context: ./php/74
    #   dockerfile: Dockerfile
    # image: custom-php-fpm:7.4
    image: bitnami/php-fpm:7.4.33
    volumes:
      - /data/ebc:/app/ebc
      - ./php/php.ini:/opt/bitnami/php/etc/php.ini:ro
      - ./php/74/www.conf:/opt/bitnami/php/etc/php-fpm.d/www.conf
      - ./php/74/log:/var/log
      - /data/ebc/config.php:/app/ebc/config.php:ro
      - /data/ebc/MctBackend/config.php:/app/ebc/MctBackend/config.php:ro
      - /data/ebc/MCTWEBMGT/config.php:/app/ebc/MCTWEBMGT/config.php:ro
      - /data/ebc/PartnerZone/config.php:/app/ebc/PartnerZone/config.php:ro
    restart: always